name: npm-publish

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      VERSION_TYPE:
        description: 'Version type to bump (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Bump version and push tag
        run: |
          git config --global user.email "dpohvar@gmail.com"
          git config --global user.name "GITHUB_ACTIONS"
          npm version $VERSION_TYPE -m "Bump version to %s [skip ci]"
          git push origin main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_TYPE: ${{ inputs.VERSION_TYPE }}

      - name: Install (npm)
        run: npm clean-install

      - name: Build (npm)
        run: npm run build

      - name: Publish (npm)
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_FLINBEIN }}


